-- ─────────────────────────────────────────────────────────────────────────────
-- FCI plemena psů — rozšíření číselníku animal_breeds
-- Přidává FCI skupinu, původní název v zemi původu a oficiální českou zkratku.
-- Bezpečné opakované spuštění (IF NOT EXISTS, ON CONFLICT DO NOTHING).
-- ─────────────────────────────────────────────────────────────────────────────

-- ── 1. Rozšíření schématu animal_breeds ──────────────────────────────────────
ALTER TABLE animal_breeds ADD COLUMN IF NOT EXISTS fci_group              TEXT;
ALTER TABLE animal_breeds ADD COLUMN IF NOT EXISTS original_name          TEXT;
ALTER TABLE animal_breeds ADD COLUMN IF NOT EXISTS official_abbreviation  TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'animal_breeds_fci_group_check'
  ) THEN
    ALTER TABLE animal_breeds
      ADD CONSTRAINT animal_breeds_fci_group_check
      CHECK (fci_group IS NULL OR fci_group IN (
        'I','II','III','IV','V','VI','VII','VIII','IX','X','unrecognized'
      ));
  END IF;
END $$;

-- Unikátnost (species_id, name_cs) — pro bezpečný ON CONFLICT při seedování
CREATE UNIQUE INDEX IF NOT EXISTS uq_animal_breeds_species_name
  ON animal_breeds (species_id, name_cs);

CREATE INDEX IF NOT EXISTS idx_animal_breeds_fci_group
  ON animal_breeds (fci_group) WHERE fci_group IS NOT NULL;

-- ── 2. Seed FCI plemen ───────────────────────────────────────────────────────
DO $$
DECLARE
  dog_id UUID;
BEGIN
  SELECT id INTO dog_id
    FROM animal_species
   WHERE name_cs ILIKE '%pes%' OR name_cs ILIKE '%psi%'
   LIMIT 1;

  IF dog_id IS NULL THEN
    RAISE NOTICE 'Druh "pes" nenalezen v animal_species, seed přeskočen.';
    RETURN;
  END IF;

  INSERT INTO animal_breeds (species_id, name_cs, original_name, official_abbreviation, fci_group) VALUES
  -- ── FCI I. – Ovčáci a honáčtí psi ──────────────────────────────────────────
  (dog_id, 'Australská kelpie',                              'Australian Kelpie',                            'AKE', 'I'),
  (dog_id, 'Australský ovčák',                               'Australian Shepherd',                          'AUO', 'I'),
  (dog_id, 'Bearded kolie',                                  'Bearded Collie',                               'BD',  'I'),
  (dog_id, 'Beauceron',                                      'Berger de Beauce',                             'BC',  'I'),
  (dog_id, 'Belgický ovčák',                                 'Chien de Berger Belge',                        'BOO', 'I'),
  (dog_id, 'Belgický ovčák – Groenendael',                   'Chien de Berger Belge – Groenendael',          'BOG', 'I'),
  (dog_id, 'Belgický ovčák – Laekenois',                     'Chien de Berger Belge – Laekenois',            'BOL', 'I'),
  (dog_id, 'Belgický ovčák – Malinois',                      'Chien de Berger Belge – Malinois',             'BOM', 'I'),
  (dog_id, 'Belgický ovčák – Tervueren',                     'Chien de Berger Belge – Tervueren',            'BOT', 'I'),
  (dog_id, 'Bergamský ovčák',                                'Cane da Pastore Bergamasco',                   'BEO', 'I'),
  (dog_id, 'Bobtail',                                        'Old English Sheepdog',                         'BOB', 'I'),
  (dog_id, 'Border kolie',                                   'Border Collie',                                'BOC', 'I'),
  (dog_id, 'Briard',                                         'Berger de Brie',                               'BRI', 'I'),
  (dog_id, 'Cao de Serra de Aires',                          'Cao de Serra de Aires',                        'CSA', 'I'),
  (dog_id, 'Chodský pes',                                    'Chodský pes',                                  'CHP', 'I'),
  (dog_id, 'Flanderský bouvier',                             'Bouvier des Flandres',                         'FBO', 'I'),
  (dog_id, 'Holandský ovčácký pudl',                         'Schapendoes',                                  'SCA', 'I'),
  (dog_id, 'Holandský ovčák',                                'Hollandse Herdershond',                        'HHO', 'I'),
  (dog_id, 'Holandský ovčák dlouhosrstý',                    'Hollandse Herdershond',                        'HHD', 'I'),
  (dog_id, 'Holandský ovčák krátkosrstý',                    'Hollandse Herdershond Korthaar',               'HHK', 'I'),
  (dog_id, 'Chien Fila de Saint Miguel',                     'Chien Fila de Saint Miguel',                   'FSM', 'I'),
  (dog_id, 'Chorvatský ovčák',                               'Hrvatski Ovčar',                               'CHO', 'I'),
  (dog_id, 'Jihoruský ovčák',                                'Ioujnorousskaia Ovtcharka',                    'JRO', 'I'),
  (dog_id, 'Katalánský ovčák',                               'Gos d''Atura Catala',                          'KTO', 'I'),
  (dog_id, 'Kolie dlouhosrstá',                              'Collie Rough',                                 'CD',  'I'),
  (dog_id, 'Kolie krátkosrstá',                              'Collie Smooth',                                'CK',  'I'),
  (dog_id, 'Komondor',                                       'Komondor',                                     'KOM', 'I'),
  (dog_id, 'Krašský ovčák',                                  'Kraski ovčar',                                 'KRO', 'I'),
  (dog_id, 'Kuvasz',                                         'Kuvasz',                                       'KUV', 'I'),
  (dog_id, 'Malorský ovčák',                                 'P.de Past.Mallorquín (P.d.C.de Bestiar)',      'CB',  'I'),
  (dog_id, 'Maremmansko-abruzský pastevecký pes',            'Cane da Pastore Maremmano-Abruzzese',          'MAP', 'I'),
  (dog_id, 'Mudi',                                           'Mudi',                                         'MUD', 'I'),
  (dog_id, 'Německý ovčák',                                  'Deutscher Schäferhund',                        'DS',  'I'),
  (dog_id, 'Pikardský ovčák',                                'Berger de Picardie',                           'BPI', 'I'),
  (dog_id, 'Podhalaňský ovčák',                              'Polski Owczarek Podhalanski',                  'POO', 'I'),
  (dog_id, 'Polský ovčák nížinný',                           'Polski Owczarek Nizinny',                      'PON', 'I'),
  (dog_id, 'Puli',                                           'Puli',                                         'PUL', 'I'),
  (dog_id, 'Pumi',                                           'Pumi',                                         'PUM', 'I'),
  (dog_id, 'Pyrenejský ovčák s dl. srstí v obličeji',        'Berger des Pyrénées á poil long',              'POD', 'I'),
  (dog_id, 'Pyrenejský ovčák s kr. srstí v obličeji',        'Chien de Berger des Pyrénées á face rase',     'POK', 'I'),
  (dog_id, 'Saarlosův vlčák',                                'Saarloos Wolfhond',                            'SAV', 'I'),
  (dog_id, 'Sheltie',                                        'Shetland Sheepdog',                            'SHE', 'I'),
  (dog_id, 'Slovenský čuvač',                                'Slovenský čuvač',                              'SC',  'I'),
  (dog_id, 'Šiperka',                                        'Schipperke',                                   'SIP', 'I'),
  (dog_id, 'Welsh Corgi Cardigan',                           'Welsh Corgi Cardigan',                         'WCC', 'I'),
  (dog_id, 'Welsh Corgi Pembroke',                           'Welsh Corgi Pembroke',                         'WCP', 'I'),

  -- ── FCI II. – Pinčové a knírači, molossoidní ──────────────────────────────
  (dog_id, 'Aidi',                                           'Aidi',                                         'AID', 'II'),
  (dog_id, 'Anatolský pastevecký pes',                       'Coban Cöpegi',                                 'APP', 'II'),
  (dog_id, 'Anglický buldok',                                'Bulldog',                                      'AB',  'II'),
  (dog_id, 'Anglický mastif',                                'Mastiff',                                      'EM',  'II'),
  (dog_id, 'Appenzellský salašnický pes',                    'Appenzeller Sennenhund',                       'APZ', 'II'),
  (dog_id, 'Argentinská doga',                               'Dogo Argentino',                               'AD',  'II'),
  (dog_id, 'Bernský salašnický pes',                         'Berner Sennenhund',                            'BSP', 'II'),
  (dog_id, 'Bordeauxská doga',                               'Dogue de Bordeaux',                            'BX',  'II'),
  (dog_id, 'Brazilská fila',                                 'Fila Brasileiro',                              'FIB', 'II'),
  (dog_id, 'Bullmastif',                                     'Bullmastiff',                                  'BM',  'II'),
  (dog_id, 'Cao de Castro Laboreiro',                        'Cao de Castro Laboreiro',                      'CCL', 'II'),
  (dog_id, 'Černý terier',                                   'Tchiorny Terrier',                             'CET', 'II'),
  (dog_id, 'Dánská doga (Broholmer)',                        'Broholmer',                                    'BR',  'II'),
  (dog_id, 'Dobrman',                                        'Dobermann',                                    'DB',  'II'),
  (dog_id, 'Estrelský pastevecký pes',                       'Cao da Serra da Estrela',                      'EPP', 'II'),
  (dog_id, 'Etlenbuchský salašnický pes',                    'Etlenbucher Sennenhund',                       'ESP', 'II'),
  (dog_id, 'Holandský pinč',                                 'Hollandse Smoushond',                          'HP',  'II'),
  (dog_id, 'Hovawart',                                       'Hovawart',                                     'HW',  'II'),
  (dog_id, 'Italský corso pes',                              'Cane Corso Italiano',                          'CC',  'II'),
  (dog_id, 'Kanárská doga',                                  'Dogo Canario',                                 'PPC', 'II'),
  (dog_id, 'Kavkazský pastevecký pes',                       'Kavkazskaia Ovtcharka',                        'KAO', 'II'),
  (dog_id, 'Knírač malý',                                    'Zwergschnauzer',                               'KM',  'II'),
  (dog_id, 'Knírač malý bílý',                               'Zwergschnauzer Weiss',                         'KM',  'II'),
  (dog_id, 'Knírač malý černostříbřitý',                     'Zwergschnauzer Schwarz-Silber',                'KM',  'II'),
  (dog_id, 'Knírač malý černý',                              'Zwergschnauzer Schwarz',                       'KM',  'II'),
  (dog_id, 'Knírač malý pepř a sůl',                         'Zwergschnauzer Pfeffersalz',                   'KM',  'II'),
  (dog_id, 'Knírač střední',                                 'Schnauzer',                                    'KS',  'II'),
  (dog_id, 'Knírač střední černý',                           'Schnauzer Schwarz',                            'KS',  'II'),
  (dog_id, 'Knírač střední pepř a sůl',                      'Schnauzer Pfeffersalz',                        'KS',  'II'),
  (dog_id, 'Knírač velký',                                   'Riesenschnauzer',                              'KV',  'II'),
  (dog_id, 'Knírač velký černý',                             'Reisenschnauzer Schwarz',                      'KV',  'II'),
  (dog_id, 'Knírač velký pepř a sůl',                        'Reisenschnauzer Pfeffersalz',                  'KV',  'II'),
  (dog_id, 'Landseer',                                       'Landseer',                                     'LS',  'II'),
  (dog_id, 'Leonberger',                                     'Leonberger',                                   'L',   'II'),
  (dog_id, 'Neapolský mastin',                               'Mastino Napoletano',                           'NM',  'II'),
  (dog_id, 'Německá doga',                                   'Deutsche Dogge',                               'ND',  'II'),
  (dog_id, 'Německý boxer',                                  'Deutscher Boxer',                              'BOX', 'II'),
  (dog_id, 'Německý pinč',                                   'Pinscher',                                     'NP',  'II'),
  (dog_id, 'Novofundlandský pes',                            'Newfoundland',                                 'NF',  'II'),
  (dog_id, 'Opičí pinč',                                     'Affenpinscher',                                'OP',  'II'),
  (dog_id, 'Perro de Presa Mallorquin',                      'Perro de Presa Mallorquin',                    'PPM', 'II'),
  (dog_id, 'Pyrenejský horský pes',                          'Chien de Montagne des Pyrénées',               'PHP', 'II'),
  (dog_id, 'Pyrenejský mastin',                              'Mastin de los Pirineos',                       'PM',  'II'),
  (dog_id, 'Rafeiro do Alentejo',                            'Rafeiro do Alentejo',                          'RA',  'II'),
  (dog_id, 'Rakouský krátkosrstý pinč',                      'Oesterreichischer Kurzhaariger Pinscher',      'RKP', 'II'),
  (dog_id, 'Rotvajler',                                      'Rottweiler',                                   'RTW', 'II'),
  (dog_id, 'Shar-Pei',                                       'Shar Pei',                                     'SP',  'II'),
  (dog_id, 'Středoasijský pastevecký pes',                   'Sredneasiatskaia Ovtcharka',                   'SAO', 'II'),
  (dog_id, 'Svatobernardský pes dlouhosrstý',                'St. Bernardshund Langhaaring',                 'SB',  'II'),
  (dog_id, 'Svatobernardský pes krátkosrstý',                'St. Bernardshund Kurzhaaring',                 'SB',  'II'),
  (dog_id, 'Svatobernarský pes',                             'St. Bernardshund',                             'SB',  'II'),
  (dog_id, 'Šarplaninský pastevecký pes',                    'Jugoslavenski Ovcarski Pas – Sarplaninac',     'JOS', 'II'),
  (dog_id, 'Španělský mastin',                               'Mastín Espaňol',                               'ME',  'II'),
  (dog_id, 'Tibetská doga',                                  'Tibetan Mastiff',                              'TD',  'II'),
  (dog_id, 'Tosa-Inu',                                       'Tosa',                                         'TI',  'II'),
  (dog_id, 'Trpasličí pinč',                                 'Zwergpinscher',                                'MHP', 'II'),
  (dog_id, 'Velký japonský pes',                             'Great Japanese Dog',                           'VJP', 'II'),
  (dog_id, 'Velký švýcarský salašnický pes',                 'Grosser Schweizer Sennenhund',                 'VSP', 'II'),

  -- ── FCI III. – Teriéři ────────────────────────────────────────────────────
  (dog_id, 'Airedale terier (Erdelteriér)',                  'Airedale Terrier',                             'AT',  'III'),
  (dog_id, 'Americký stafordširský terier',                  'American Staffordshire Terrier',               'AST', 'III'),
  (dog_id, 'Anglický toy terier',                            'Toy Terrier',                                  'ATT', 'III'),
  (dog_id, 'Australský Silky terier',                        'Australian Silky Terrier',                     'SIT', 'III'),
  (dog_id, 'Australský terier',                              'Australian Terrier',                           'AUT', 'III'),
  (dog_id, 'Bedlington terier',                              'Bedlington Terrier',                           'BDT', 'III'),
  (dog_id, 'Border terier',                                  'Border Terrier',                               'BRT', 'III'),
  (dog_id, 'Brazilský terier',                               'Brasilian Terrier',                            'BRA', 'III'),
  (dog_id, 'Bullterier',                                     'Bullterrier',                                  'BT',  'III'),
  (dog_id, 'Bullterier (Normal size)',                       'English Bull Terrier – Normal size',           'BT',  'III'),
  (dog_id, 'Cairn Terier',                                   'Cairn Terrier',                                'CR',  'III'),
  (dog_id, 'Český terier',                                   'Český Terrier',                                'CT',  'III'),
  (dog_id, 'Dandie Dinmont terier',                          'Dandie Dinmont Terrier',                       'DDT', 'III'),
  (dog_id, 'Foxterier drsnosrstý',                           'Fox Terrier Wire',                             'FXD', 'III'),
  (dog_id, 'Foxterier hladkosrstý',                          'Fox Terrier Smooth',                           'FXH', 'III'),
  (dog_id, 'Irish Glen of Imaal terier',                     'Irish Glen of Imaal Terrier',                  'GIT', 'III'),
  (dog_id, 'Irský jemnosrstý pšeničný teriér',               'Irish Soft Coated Wheaten Terrier',            'SCT', 'III'),
  (dog_id, 'Irský terier',                                   'Irish Terrier',                                'IRT', 'III'),
  (dog_id, 'Jack Russell Teriér',                            'Jack Russell Terrier',                         'JRT', 'III'),
  (dog_id, 'Japonský terier',                                'Nihon Teria',                                  'JT',  'III'),
  (dog_id, 'Kerry blue terier',                              'Kerry Blue Terrier',                           'KBT', 'III'),
  (dog_id, 'Lakeland terier',                                'Lakeland Terrier',                             'LT',  'III'),
  (dog_id, 'Manchester terier',                              'Manchester Terrier',                           'MT',  'III'),
  (dog_id, 'Miniaturní bullterier',                          'English Bull Terrier – Miniature size',        'MBT', 'III'),
  (dog_id, 'Německý lovecký terier (Jagdteriér)',            'Deutscher Jagdterrier',                        'JGT', 'III'),
  (dog_id, 'Norfolk terier',                                 'Norfolk Terrier',                              'NFT', 'III'),
  (dog_id, 'Norwich terier',                                 'Norwich Terrier',                              'NOT', 'III'),
  (dog_id, 'Parson Russell Teriér',                          'Parson Russell Terrier',                       'PJR', 'III'),
  (dog_id, 'Sealyham terier',                                'Sealyham Terrier',                             'SET', 'III'),
  (dog_id, 'Skotský terier',                                 'Scottish Terrier',                             'ST',  'III'),
  (dog_id, 'Skye terier',                                    'Skye Terrier',                                 'SKY', 'III'),
  (dog_id, 'Stafordšírský bullterier',                       'Staffordshire Bullterrier',                    'SBT', 'III'),
  (dog_id, 'Welsh terier',                                   'Welsh Terrier',                                'WT',  'III'),
  (dog_id, 'West Highland White Terrier',                    'West Highland White Terrier',                  'WHW', 'III'),
  (dog_id, 'Yorkšírský (jorkšírský) terier',                 'Yorkshire Terrier',                            'YT',  'III'),

  -- ── FCI IV. – Jezevčíci ───────────────────────────────────────────────────
  (dog_id, 'Jezevčík',                                       'Dachshund',                                    'J',   'IV'),
  (dog_id, 'Jezevčík standard dlouhosrstý',                  'Dachshund Normalgrösse Langhaar',              'J',   'IV'),
  (dog_id, 'Jezevčík standard drsnosrstý',                   'Dachshund Normalgrösse Rauhhaar',              'J',   'IV'),
  (dog_id, 'Jezevčík standard hladkosrstý',                  'Dachshund Normalgrösse Kurzhaar',              'J',   'IV'),
  (dog_id, 'Jezevčík trpasličí/králičí dlouhosrstý',         'Dachshund Zwerg/Kaninchen Langhaar',           'JTK', 'IV'),
  (dog_id, 'Jezevčík trpasličí/králičí drsnosrstý',          'Dachshund Zwerg/Kaninchen Rauhhaar',           'JTK', 'IV'),
  (dog_id, 'Jezevčík trpasličí/králičí hladkosrstý',         'Dachshund Zwerg/Kaninchen Kurzhaar',           'JTK', 'IV'),

  -- ── FCI V. – Špicové a primitivní typy ────────────────────────────────────
  (dog_id, 'Akita-Inu',                                      'Akita',                                        'AI',  'V'),
  (dog_id, 'Aljašský malamut',                               'Alaskan Malamute',                             'AM',  'V'),
  (dog_id, 'Basenji',                                        'Basenji',                                      'BSN', 'V'),
  (dog_id, 'Burgoský perdiquero',                            'Perdiquero de Burgos',                         'BUP', 'V'),
  (dog_id, 'Canaanský pes',                                  'Canaan dog',                                   'CA',  'V'),
  (dog_id, 'Eurasier',                                       'Eurasier',                                     'EUR', 'V'),
  (dog_id, 'Faraónský pes',                                  'Pharaoh Hound',                                'FC',  'V'),
  (dog_id, 'Finský špic',                                    'Suomenpystkorva',                              'FS',  'V'),
  (dog_id, 'Grónský pes',                                    'Grönlandshund',                                'GP',  'V'),
  (dog_id, 'Hokkaido-Ken',                                   'Hokkaido',                                     'HOK', 'V'),
  (dog_id, 'Čau Čau',                                        'Chow chow',                                    'CHW', 'V'),
  (dog_id, 'Ibizský podenco',                                'Podenco Ibizenco',                             'IP',  'V'),
  (dog_id, 'Islandský pes',                                  'Islandsk Farehond',                            'ISP', 'V'),
  (dog_id, 'Italský volpino',                                'Volpino Italiano',                             'IV',  'V'),
  (dog_id, 'Jaemthund',                                      'Jämthund',                                     'JA',  'V'),
  (dog_id, 'Japonský špic',                                  'Nihon Supittsu',                               'JSP', 'V'),
  (dog_id, 'Kai-Inu',                                        'Kai',                                          'KAI', 'V'),
  (dog_id, 'Kanárský podenco',                               'Podenco Canario',                              'PC',  'V'),
  (dog_id, 'Karelský medvědí pes',                           'Karjalankarhukoira',                           'KMP', 'V'),
  (dog_id, 'Kishu-Inu',                                      'Kishu',                                        'KII', 'V'),
  (dog_id, 'Korejský Jindo Dog',                             'Korea Jindo Dog',                              'KJ',  'V'),
  (dog_id, 'Lapinkoira',                                     'Suomenlapinkoira',                             'LAK', 'V'),
  (dog_id, 'Lapinporokoira',                                 'Lapinporokoira (Lapponian Herder)',            'LAI', 'V'),
  (dog_id, 'Laponský pes',                                   'Ruotsinlapinkoira (Lapphund)',                 'LAP', 'V'),
  (dog_id, 'Mexický naháč',                                  'Xoloitzcuintle',                               'MEN', 'V'),
  (dog_id, 'Německý špic',                                   'Deutscher Spitz',                              'NS',  'V'),
  (dog_id, 'Německý špic malý',                              'Deutscher Spitz – Kleinspitz',                 'NS',  'V'),
  (dog_id, 'Německý špic střední',                           'Deutscher Spitz – Mittelspitz',                'NS',  'V'),
  (dog_id, 'Německý špic trpasličí',                         'Deutscher Spitz – Zwergspitz',                 'NS',  'V'),
  (dog_id, 'Německý špic velký',                             'Deutscher Spitz – Grosspitz',                  'NS',  'V'),
  (dog_id, 'Německý špic vlčí',                              'Deutscher Spitz – Wolfspitz',                  'NS',  'V'),
  (dog_id, 'Norbotenský špic',                               'Norrbottenspets',                              'NBS', 'V'),
  (dog_id, 'Norský buhund',                                  'Norsk Buhund',                                 'NB',  'V'),
  (dog_id, 'Norský losí pes černý',                          'Norsk Elghund Sort',                           'NLC', 'V'),
  (dog_id, 'Norský losí pes šedý',                           'Elghund Grä',                                  'NLS', 'V'),
  (dog_id, 'Norský lundehund',                               'Norsk Lundehund',                              'NL',  'V'),
  (dog_id, 'Peruánský naháč',                                'Perro Sin Pelo del Perú',                      'PEN', 'V'),
  (dog_id, 'Portugalský podengo',                            'Podengo Portugues',                            'POP', 'V'),
  (dog_id, 'Ruskoevropská lajka',                            'Laika Russko-Evropeiskaia',                    'REL', 'V'),
  (dog_id, 'Samojed',                                        'Samoyede',                                     'S',   'V'),
  (dog_id, 'Shiba-Inu',                                      'Shiba',                                        'SI',  'V'),
  (dog_id, 'Shikoku-Inu',                                    'Shikoku',                                      'SHK', 'V'),
  (dog_id, 'Sibiřský husky',                                 'Siberian Husky',                               'SH',  'V'),
  (dog_id, 'Sicilský chrt',                                  'Cirneco dell'' Etna',                          'CE',  'V'),
  (dog_id, 'Thajský ridgeback',                              'Thailand-Ridgeback',                           'TR',  'V'),
  (dog_id, 'Východosibiřská lajka',                          'Laika Vostotchno-Sibirskaia',                  'VSL', 'V'),
  (dog_id, 'Západosibiřská lajka',                           'Laika Zapadno-Sibirskaia',                     'ZSL', 'V'),

  -- ── FCI VI. – Honiči, barváři a příbuzná plemena ──────────────────────────
  (dog_id, 'Americký foxhound',                              'American Fox Hound',                           'AMF', 'VI'),
  (dog_id, 'Angl.-franc. honič de Petite Venerie',           'Anglo-Francais de Petite Venerie',             'AFP', 'VI'),
  (dog_id, 'Ariégois',                                       'Ariégois',                                     'AR',  'VI'),
  (dog_id, 'Artésko-normandský basset',                      'Basset Artésien Normand',                      'ANB', 'VI'),
  (dog_id, 'Artoisský basset',                               'Basset d''Artois',                             'ARB', 'VI'),
  (dog_id, 'Artoisský honič',                                'Chien d''Artois',                              'AH',  'VI'),
  (dog_id, 'Balkánský honič',                                'Balkanski Gonič',                              'BHO', 'VI'),
  (dog_id, 'Basset Hound',                                   'Basset Hound',                                 'BH',  'VI'),
  (dog_id, 'Bavorský barvář',                                'Bayrischer Gebirgsschweisshund',               'BB',  'VI'),
  (dog_id, 'Beagle (Bígl)',                                  'Beagle',                                       'BEA', 'VI'),
  (dog_id, 'Beagle Harrier',                                 'Beagle Harrier',                               'BEH', 'VI'),
  (dog_id, 'Billy',                                          'Billy',                                        'BIL', 'VI'),
  (dog_id, 'Black and Tan Coonhound',                        'Black and Tan Coonhound',                      'BTC', 'VI'),
  (dog_id, 'Bloodhound',                                     'Chien de Saint Hubert',                        'BL',  'VI'),
  (dog_id, 'Bosenský hrubosrstý honič',                      'Bosanski Oštrodlaki Gonič – Barak',            'BHH', 'VI'),
  (dog_id, 'Brakýř jezevčíkovitý',                           'Alpenländische Dachsbracke',                   'BJ',  'VI'),
  (dog_id, 'Briquet Griffon Vendéen',                        'Briquet Griffon Vendéen',                      'BGV', 'VI'),
  (dog_id, 'Dalmatin',                                       'Dalmatiner',                                   'DA',  'VI'),
  (dog_id, 'Drever',                                         'Drever',                                       'DR',  'VI'),
  (dog_id, 'Dunker',                                         'Dunker',                                       'DU',  'VI'),
  (dog_id, 'Finský honič',                                   'Suomenajakoira',                               'FH',  'VI'),
  (dog_id, 'Francouzský bílo-černý honič',                   'Francais Blanc et Noir',                       'FBC', 'VI'),
  (dog_id, 'Francouzský bílo-oranžový honič',                'Francais Blanc et Orange',                     'FBH', 'VI'),
  (dog_id, 'Francouzský trikolorní honič',                   'Francais Tricolore',                           'FTH', 'VI'),
  (dog_id, 'Gaskoňsko-saintgeoiský honič',                   'Gascon Saintgeois',                            'GSH', 'VI'),
  (dog_id, 'Haldenův honič',                                 'Haldenstöver',                                 'HHO', 'VI'),
  (dog_id, 'Hamiltonův honič',                               'Hamiltonstövare',                              'HA',  'VI'),
  (dog_id, 'Hannoverský barvář',                             'Hannover''scher Schweisshund',                 'HB',  'VI'),
  (dog_id, 'Harrier',                                        'Harrier',                                      'HAR', 'VI'),
  (dog_id, 'Hygenův honič',                                  'Hygenhund',                                    'HYH', 'VI'),
  (dog_id, 'Istrijský hrubosrstý honič',                     'Istarski Ostrodlaki Gonič',                    'IHH', 'VI'),
  (dog_id, 'Istrijský krátkosrstý honič',                    'Istarski Kratkodlaki Gonič',                   'IKH', 'VI'),
  (dog_id, 'Italský Segugio',                                'Segugio Italiano',                             'SE',  'VI'),
  (dog_id, 'Italský Segugio krátkosrstý',                    'Segugio Italiano a pelo raso',                 'SEK', 'VI'),
  (dog_id, 'Jugoslávský planinský honič',                    'Jugoslavenski Planinski Gonič',                'JPH', 'VI'),
  (dog_id, 'Jugoslávský trikolorní honič',                   'Jugoslavenski Trojbojni Gonič',                'JTH', 'VI'),
  (dog_id, 'Malý gaskoňsko-saintgeoisský honič',             'Gascon Saintgeois Petite taille',              'GSM', 'VI'),
  (dog_id, 'Malý hrubosrstý modrý gaskoňský honič',          'Griffon Bleu de Gascogne',                     'MHG', 'VI'),
  (dog_id, 'Malý hrubosrstý vendéeský basset',               'Petit Basset Griffon Vendéen',                 'PBG', 'VI'),
  (dog_id, 'Malý modrý gaskoňský honič',                     'Petit Bleu de Gascogne',                       'MMG', 'VI'),
  (dog_id, 'Modrý gaskoňský basset',                         'Basset Bleu de Gascogne',                      'BBG', 'VI'),
  (dog_id, 'Německý honič',                                  'Deutsche Bracke',                              'NHO', 'VI'),
  (dog_id, 'Nivernaisský hrubosrstý honič',                  'Griffon Nivernais',                            'NHH', 'VI'),
  (dog_id, 'Otterhound (Vydrař)',                            'Otterhound',                                   'OTT', 'VI'),
  (dog_id, 'Plavý bretaňský basset',                         'Basset Fauve de Bretagne',                     'PBB', 'VI'),
  (dog_id, 'Plavý bretaňský honič',                          'Griffon Fauve de Bretagne',                    'PBH', 'VI'),
  (dog_id, 'Poitevin',                                       'Poitevin',                                     'POI', 'VI'),
  (dog_id, 'Polský ogar',                                    'Polski ogar',                                  'PO',  'VI'),
  (dog_id, 'Porcelaine',                                     'Porcelaine',                                   'POR', 'VI'),
  (dog_id, 'Posávský honič',                                 'Posavski Gonič',                               'PHO', 'VI'),
  (dog_id, 'Rakouský krátkosrstý honič',                     'Brandlbracke',                                 'RKH', 'VI'),
  (dog_id, 'Rhodézský ridgeback',                            'Rhodesian ridgeback',                          'RR',  'VI'),
  (dog_id, 'Řecký honič',                                    'Hellinikos Ichnilatis',                        'RH',  'VI'),
  (dog_id, 'Sedmihradský honič',                             'Erdélyi kopó',                                 'SEH', 'VI'),
  (dog_id, 'Schillerův honič',                               'Schillerstövare',                              'SCH', 'VI'),
  (dog_id, 'Slovenský kopov',                                'Slovenský kopov',                              'SK',  'VI'),
  (dog_id, 'Smalandský honič',                               'Smalandsstövare',                              'SMH', 'VI'),
  (dog_id, 'Španělský sabueso',                              'Sabueso Espaňol',                              'SPS', 'VI'),
  (dog_id, 'Štýrský brakýř',                                 'Steirische Rauhhaarige Hochgebirgsbracke',     'BS',  'VI'),
  (dog_id, 'Švýc.n.honič – Bernský nízkonohý honič',         'Schweiz. Niederl.- Berner Niederlaufhund',     'SNH', 'VI'),
  (dog_id, 'Švýc.n.honič – Lucernský nízkonohý honič',       'Schweiz.Niederl.- Luzerner Niederlaufh.',      'SNH', 'VI'),
  (dog_id, 'Švýc.níz.honič – Petit Courant du Jura',         'Schweiz.Nieder.- Petit Courant de Jura',       'SNH', 'VI'),
  (dog_id, 'Švýcar.n.honič – Švycký nízkonohý honič',        'Schw.Niederl.- Schwytzer Niederlaufhund',      'SNH', 'VI'),
  (dog_id, 'Švýcarský honič',                                'Schweizer Laufhund',                           'SVH', 'VI'),
  (dog_id, 'Švýcarský honič – Bernský honič',                'Schweizer Laufh.- Berner Laufhund',            'BRH', 'VI'),
  (dog_id, 'Švýcarský honič – Jurský honič',                 'Schweizer Laufh. – Bruno du Jura',             'SVH', 'VI'),
  (dog_id, 'Švýcarský honič – Lucernský honič',              'Schweizer Laufh.- Luzerner Laufhund',          'LZH', 'VI'),
  (dog_id, 'Švýcarský honič – Švycký honič',                 'Schweizer Laufh.-Schwytzer Laufh.',            'SVH', 'VI'),
  (dog_id, 'Švýcarský nízkonohý honič',                      'Schweizer Niederlaufhund',                     'SNH', 'VI'),
  (dog_id, 'Tyrolský honič',                                 'Tyroler Bracke',                               'TH',  'VI'),
  (dog_id, 'Vel.franc.-anglický bílo-oranžový honič',        'Grand Anglo-Francais Blanc et Orange',         'VFO', 'VI'),
  (dog_id, 'Vel.francouzsko-anglický trikolor.honič',        'Grand Anglo-Francais Tricolore',               'VFT', 'VI'),
  (dog_id, 'Velký franc.-anglický bílo-černý honič',         'Grand Anglo-Francais Blanc et Noir',           'VFC', 'VI'),
  (dog_id, 'Velký gaskoňsko-saintongeoisský honič',          'Gascon Saintongeois Grande taille',            'GSV', 'VI'),
  (dog_id, 'Velký hrubosrstý vendéeský basset',              'Grand Basset Griffon Vendéen',                 'GBG', 'VI'),
  (dog_id, 'Velký modrý gaskoňský honič',                    'Grand Bleu de Gascogne',                       'VMG', 'VI'),
  (dog_id, 'Velký vendéeský hrubosrstý honič',               'Grand Griffon Vendéen',                        'VVH', 'VI'),
  (dog_id, 'Westfálský jezevčíkovitý honič',                 'Westfälische Dachsbracke',                     'WJH', 'VI'),

  -- ── FCI VII. – Ohaři ──────────────────────────────────────────────────────
  (dog_id, 'Anglický setr',                                  'English Setter',                               'AS',  'VII'),
  (dog_id, 'Ariegský ohař krátkosrstý',                      'Braque d l''Ariége',                           'AO',  'VII'),
  (dog_id, 'Auvergneský ohař krátkosrstý',                   'Braque d'' Auvergne',                          'BA',  'VII'),
  (dog_id, 'Bourbonský ohař krátkosrstý',                    'Braque du Bourbonnais',                        'BOH', 'VII'),
  (dog_id, 'Braque Dupuy',                                   'Braque Dupuy',                                 'BRD', 'VII'),
  (dog_id, 'Bretaňský ohař dlouhosrstý',                     'Epagneul Breton',                              'EB',  'VII'),
  (dog_id, 'Český fousek',                                   'Český fousek',                                 'CF',  'VII'),
  (dog_id, 'Dánský ohař krátkosrstý',                        'Gammel Dansk Honsehund',                       'DKO', 'VII'),
  (dog_id, 'Dlouhosrstý ohař z Pont-Audemer',                'Epagneul de Pont-Audemer',                     'EPA', 'VII'),
  (dog_id, 'Drentsche Patrisijshond',                        'Drentsche Patrisijshond',                      'DPH', 'VII'),
  (dog_id, 'Francouzský ohař dlouhosrstý',                   'Epagneul Francais',                            'EF',  'VII'),
  (dog_id, 'Francouzský ohař krátkosrstý gaskoň. typu',      'Braque Francais Type Gascogne',                'BRF', 'VII'),
  (dog_id, 'Francouzský ohař krátkosrstý pyren. typu',       'Braque Francais Type Pyrénées',                'BFP', 'VII'),
  (dog_id, 'Frízský ohař (Stabyhoun)',                       'Friesischer Vorstehhund (Stabyhoun)',          'STA', 'VII'),
  (dog_id, 'Gordonsetr',                                     'Gordon Setter',                                'GS',  'VII'),
  (dog_id, 'Griffon á poil laineux',                         'Griffon á poil laineux',                       'GPL', 'VII'),
  (dog_id, 'Griffon d''Arrét á Poil Dur',                    'Griffon d''Arrét á Poil Dur',                  'GA',  'VII'),
  (dog_id, 'Irský červenobílý setr',                         'Irish Red & White Setter',                     'RWS', 'VII'),
  (dog_id, 'Irský setr',                                     'Irish Red Setter',                             'IS',  'VII'),
  (dog_id, 'Italský ohař',                                   'Bracco Italiano',                              'IO',  'VII'),
  (dog_id, 'Italský spinone',                                'Spinone Italiano',                             'SPI', 'VII'),
  (dog_id, 'Maďarský ohař drátosrstý',                       'Drotzörü Magyar Vizsla',                       'MOD', 'VII'),
  (dog_id, 'Maďarský ohař krátkosrstý',                      'Rövidszörü Magyar Viszla',                     'MOK', 'VII'),
  (dog_id, 'Malý münsterlandský ohař',                       'Kleiner Münsterländer Vorstehhund',            'MMO', 'VII'),
  (dog_id, 'Modrý pikardský ohař dlouhosrstý',               'Epagneul Bleu de Picardie',                    'MPO', 'VII'),
  (dog_id, 'Německý ohař dlouhosrstý',                       'Deutscher Langhaariger Vorstehhund',           'DO',  'VII'),
  (dog_id, 'Německý ohař drátosrstý',                        'Deutscher Drahthaariger Vorstehhund',          'NDO', 'VII'),
  (dog_id, 'Německý ohař krátkosrstý',                       'Deutscher Kurzhaariger Vorstehhund',           'KO',  'VII'),
  (dog_id, 'Německý ohař ostnosrstý',                        'Deutscher Stichelhaariger Vorstehhund',        'NOO', 'VII'),
  (dog_id, 'Pikardský ohař dlouhosrstý',                     'Epagneul Picard',                              'PDO', 'VII'),
  (dog_id, 'Pointer',                                        'English Pointer',                              'POI', 'VII'),
  (dog_id, 'Portugalský ohař',                               'Perdiguero Portugués',                         'POH', 'VII'),
  (dog_id, 'Pudlpointr',                                     'Pudelpointer',                                 'PP',  'VII'),
  (dog_id, 'Saint-Germainský ohař krátkosrstý',              'Braque Saint-Germain',                         'SGO', 'VII'),
  (dog_id, 'Slovenský ohař hrubosrstý',                      'Slovenský hrubosrstý stavač',                  'SHO', 'VII'),
  (dog_id, 'Velký münsterlandský ohař',                      'Grosser Münsterländer Vorstehhund',            'VMO', 'VII'),
  (dog_id, 'Výmarský ohař',                                  'Weimaraner',                                   'VO',  'VII'),
  (dog_id, 'Výmarský ohař dlouhosrstý',                      'Weimaraner – Langhaar',                        'VOD', 'VII'),
  (dog_id, 'Výmarský ohař krátkosrstý',                      'Weimaraner – Kurzhaar',                        'VOK', 'VII'),

  -- ── FCI VIII. – Retrívři, slidiči a vodní psi ─────────────────────────────
  (dog_id, 'Americký kokršpaněl',                            'American Cocker Spaniel',                      'AK',  'VIII'),
  (dog_id, 'Americký vodní španěl',                          'American Water Spaniel',                       'AWS', 'VIII'),
  (dog_id, 'Anglický kokršpaněl',                            'English Cocker Spaniel',                       'AC',  'VIII'),
  (dog_id, 'Anglický špringr španěl',                        'English Springer Spaniel',                     'ASS', 'VIII'),
  (dog_id, 'Barbet',                                         'Barbet',                                       'BAR', 'VIII'),
  (dog_id, 'Clumber španěl',                                 'Clumber Spaniel',                              'CS',  'VIII'),
  (dog_id, 'Curly Coated Retriever',                         'Curly Coated Retriever',                       'CCR', 'VIII'),
  (dog_id, 'Field španěl',                                   'Field Spaniel',                                'FS',  'VIII'),
  (dog_id, 'Flat Coated Retriever',                          'Flat Coated Retriever',                        'FCR', 'VIII'),
  (dog_id, 'Chesapeake Bay Retriever',                       'Chesapeake Bay Retriever',                     'CBR', 'VIII'),
  (dog_id, 'Irský vodní španěl',                             'Irish Water Spaniel',                          'IWS', 'VIII'),
  (dog_id, 'Kooikerhondje',                                  'Kooikerhondje',                                'KOO', 'VIII'),
  (dog_id, 'Labradorský retriever',                          'Labrador Retriever',                           'LR',  'VIII'),
  (dog_id, 'Německý křepelák',                               'Deutscher Wachtelhund',                        'NK',  'VIII'),
  (dog_id, 'Nova Scotia Duck Tolling Retriever',             'Nova Scotia Duck Tolling Retriever',           'NSR', 'VIII'),
  (dog_id, 'Portugalský vodní pes',                          'Cao de Aqua',                                  'PVP', 'VIII'),
  (dog_id, 'Sussex španěl',                                  'Sussex Spaniel',                               'SS',  'VIII'),
  (dog_id, 'Španělský vodní pes',                            'Perro de Aqua',                                'SVP', 'VIII'),
  (dog_id, 'Welššpringršpaněl',                              'Welsh Springer Spaniel',                       'WSS', 'VIII'),
  (dog_id, 'Wetterhound',                                    'Wetterhound',                                  'W',   'VIII'),
  (dog_id, 'Zlatý retriever',                                'Golden Retriever',                             'GR',  'VIII'),

  -- ── FCI IX. – Společenská plemena a toy ───────────────────────────────────
  (dog_id, 'Belgický grifonek',                              'Griffon Belge',                                'BEG', 'IX'),
  (dog_id, 'Bišonek',                                        'Bichon á poil Frisé',                          'BF',  'IX'),
  (dog_id, 'Boloňský psík',                                  'Bolognese',                                    'BP',  'IX'),
  (dog_id, 'Bostonský terier',                               'Boston Terrier',                               'BOS', 'IX'),
  (dog_id, 'Brabantík',                                      'Petit Brabancon',                              'BAG', 'IX'),
  (dog_id, 'Bruselský grifonek',                             'Griffon Bruxellois',                           'BRG', 'IX'),
  (dog_id, 'Čínský chocholatý pes',                          'Chinese Crested Dog',                          'CIN', 'IX'),
  (dog_id, 'Čivava',                                         'Chihuahueňo',                                  'CHI', 'IX'),
  (dog_id, 'Čivava dlouhosrstá',                             'Chihuahueňo – Pelo Largo',                     'CHI', 'IX'),
  (dog_id, 'Čivava krátkosrstá',                             'Chihuahueňo – Pelo Corto',                     'CHI', 'IX'),
  (dog_id, 'Francouzský buldoček',                           'Bouledogue Francais',                          'FB',  'IX'),
  (dog_id, 'Havanský psík',                                  'Bichon Havanais',                              'HAV', 'IX'),
  (dog_id, 'Japan-chin',                                     'Chin',                                         'JCH', 'IX'),
  (dog_id, 'Kavalír King Charles španěl',                    'Cavalier King Charles Spaniel',                'CKC', 'IX'),
  (dog_id, 'King Charles španěl',                            'King Charles Spaniel',                         'KCS', 'IX'),
  (dog_id, 'Kromforländer',                                  'Kromforländer',                                'KR',  'IX'),
  (dog_id, 'Lhasa Apso',                                     'Lhasa Apso',                                   'LA',  'IX'),
  (dog_id, 'Lvíček',                                         'Petit Chien Lion',                             'LEO', 'IX'),
  (dog_id, 'Maltézský psík',                                 'Maltese',                                      'MA',  'IX'),
  (dog_id, 'Malý kontinentální španěl',                      'Epagneul Nain Continental',                    'PA',  'IX'),
  (dog_id, 'Mops',                                           'Pug',                                          'MOP', 'IX'),
  (dog_id, 'Papillon',                                       'Papillon – Epagneul Nain Continental',         'PAP', 'IX'),
  (dog_id, 'Phaléne',                                        'Phaléne – Epagneul Nain Continental',          'PH',  'IX'),
  (dog_id, 'Pekingský palácový psík',                        'Pekingese',                                    'PPP', 'IX'),
  (dog_id, 'Pudl',                                           'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl střední aprikot',                           'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl střední bílý',                              'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl střední černý',                             'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl střední hnědý',                             'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl střední stříbrný',                          'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl toy aprikot',                               'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl toy bílý',                                  'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl toy černý',                                 'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl toy hnědý',                                 'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl toy stříbrný',                              'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl trpasličí aprikot',                         'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl trpasličí bílý',                            'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl trpasličí černý',                           'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl trpasličí hnědý',                           'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl trpasličí stříbrný',                        'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl velký aprikot',                             'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl velký bílý',                                'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl velký černý',                               'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl velký hnědý',                               'Caniche',                                      'P',   'IX'),
  (dog_id, 'Pudl velký stříbrný',                            'Caniche',                                      'P',   'IX'),
  (dog_id, 'Shih-tzu',                                       'Shih Tzu',                                     'SHI', 'IX'),
  (dog_id, 'Tibetský španěl',                                'Tibetan Spaniel',                              'TS',  'IX'),
  (dog_id, 'Tibetský terier',                                'Tibetan Terrier',                              'TT',  'IX'),

  -- ── FCI X. – Chrti ────────────────────────────────────────────────────────
  (dog_id, 'Afgánský chrt',                                  'Afghan Hound',                                 'AF',  'X'),
  (dog_id, 'Anglický chrt (Greyhound)',                      'Greyhound',                                    'G',   'X'),
  (dog_id, 'Azavak',                                         'Azawakh',                                      'AZ',  'X'),
  (dog_id, 'Barzoj – ruský chrt',                            'Borzoi',                                       'B',   'X'),
  (dog_id, 'Deerhound',                                      'Deerhound',                                    'D',   'X'),
  (dog_id, 'Foxhound',                                       'English Foxhound',                             'FOH', 'X'),
  (dog_id, 'Irský vlkodav',                                  'Irish Wolfhound',                              'IW',  'X'),
  (dog_id, 'Italský chrtík',                                 'Piccolo Levriero Italiano',                    'IT',  'X'),
  (dog_id, 'Maďarský chrt',                                  'Magyar Agar',                                  'MC',  'X'),
  (dog_id, 'Polský chrt',                                    'Chart Polski',                                 'PCH', 'X'),
  (dog_id, 'Saluki – Perský chrt',                           'Saluki',                                       'SA',  'X'),
  (dog_id, 'Sloughi',                                        'Sloughi',                                      'SL',  'X'),
  (dog_id, 'Španělský galgo',                                'Galgo Epaňol',                                 'SG',  'X'),
  (dog_id, 'Whippet',                                        'Whippet',                                      'WH',  'X'),

  -- ── Neuznaná plemena FCI ──────────────────────────────────────────────────
  (dog_id, 'Americký buldok',                                'American Bulldog',                             'AG',  'unrecognized'),
  (dog_id, 'Americký Mini-Pei',                              'American Mini-Pei',                            'AMP', 'unrecognized'),
  (dog_id, 'Artésien Normand',                               'Artésien Normand',                             'AN',  'unrecognized'),
  (dog_id, 'Barevný boloňský psík',                          'Bolognese',                                    'BPB', 'unrecognized'),
  (dog_id, 'Bílá kolie',                                     'White Collie',                                 'WC',  'unrecognized'),
  (dog_id, 'Búrský buldok',                                  'Boerboel',                                     'BOE', 'unrecognized'),
  (dog_id, 'Český horský pes',                               'Český horský pes',                             'CHP', 'unrecognized'),
  (dog_id, 'Český strakatý pes',                             'Český strakatý pes',                           'CSP', 'unrecognized'),
  (dog_id, 'Dlouhosrstý vipet',                              'Silken Windsprite – LHW',                      'DV',  'unrecognized'),
  (dog_id, 'Eskymácký pes',                                  'Eskimo Dog',                                   'EP',  'unrecognized'),
  (dog_id, 'Hahoavu',                                        'Hahoavu',                                      'HH',  'unrecognized'),
  (dog_id, 'Chambray',                                       'Chambray',                                     'CHA', 'unrecognized'),
  (dog_id, 'Chortaja Borzaja',                               'Chortaja Borzaja',                             'CHB', 'unrecognized'),
  (dog_id, 'Lajka karelo-finská',                            'Laika Karelo-Finskaia',                        'KFL', 'unrecognized'),
  (dog_id, 'Levesque',                                       'Levesque',                                     'LE',  'unrecognized'),
  (dog_id, 'Louisianský leopardí pes',                       'Louisiana Catahoula',                          'LC',  'unrecognized'),
  (dog_id, 'Moskevský strážní pes',                          'Moskovskaja Storoževaja Sobaka',               'MSP', 'unrecognized'),
  (dog_id, 'Moskevský toy terier',                           'Moskovskij Dlinošerstoj Toy Terrier',          'MDT', 'unrecognized'),
  (dog_id, 'Normandský Poitevin',                            'Normand Poitevin',                             'NPO', 'unrecognized'),
  (dog_id, 'Patterdale terier',                              'Patterdale Terrier',                           'PAT', 'unrecognized'),
  (dog_id, 'Pražský krysařík',                               'Pražský krysařík',                             'PK',  'unrecognized'),
  (dog_id, 'Pudl vícebarevný',                               'Caniche',                                      'P',   'unrecognized')

  ON CONFLICT (species_id, name_cs) DO UPDATE SET
    original_name         = EXCLUDED.original_name,
    official_abbreviation = EXCLUDED.official_abbreviation,
    fci_group             = EXCLUDED.fci_group;
END $$;
